name: flow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: environment
  push:
    branches: main

jobs:
  push:
    uses: the-watchmen/gha-containr-call/.github/workflows/flow.yaml@main
    with:
      config: configr.yaml
      # using latest for now, but after stabilization, may want specify discret version for idempotency
      #
      image: tonykerz/containr-oci-push-scratch
      # creds could be required for pull, but in this case pull is public
      # in this case creds required for push...
      #
      registry-user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry-pass: ${{ secrets.REGISTRY_PASS}}
  # check:
  #   runs-on: ubuntu-latest
  #   needs: push
  #   steps:
  #     - run: echo json=${{ needs.push.outputs.json }}
  #     - run: echo jq-name=$(echo '${{ needs.push.outputs.json }}' | jq .image.name)
  #     - run: echo from-json-name=${{ fromJSON(needs.push.outputs.json).image.name }}
  setup:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - id: config
        # https://stackoverflow.com/a/68383110
        #
        run: |
          img=${{ fromJSON(needs.push.outputs.json).image.name }}
          # https://stackoverflow.com/a/48470227
          #
          json=$(jq -cn --arg _img ${img} '{ociImage: $_img}')
          echo json="${json}"
          echo "val=${json}" >> $GITHUB_OUTPUT
    outputs:
      config: ${{ steps.config.outputs.val }}
  pull:
    needs: setup
    uses: the-watchmen/gha-containr-call/.github/workflows/flow.yaml@main
    with:
      config: ${{ needs.setup.outputs.config }}
      config-format: json
      # using latest for now, but after stabilization, may want specify discret version for idempotency
      #
      image: tonykerz/containr-oci-pull-scratch
      #
      # this will trigger slightly different handling of work folder
      #
      is-checkout: false
      #
      # creds could be required for pull, but in this case pull is public
      #
      #registry-user: ${{ vars.REGISTRY_USER }}
    #secrets:
    #registry-pass: ${{ secrets.REGISTRY_PASS}}
