name: flow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: environment
  push:
    branches: main

jobs:
  containr:
    uses: the-watchmen/gha-containr-call/.github/workflows/flow.yaml@main
    with:
      config: configr.yaml
      image: tonykerz/containr-oci-push-scratch:1.1.5
      # creds could be required for pull, but in this case pull is public
      # in this case creds required for push...
      #
      registry-user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry-pass: ${{ secrets.REGISTRY_PASS}}
  next:
    runs-on: ubuntu-latest
    needs: containr
    steps:
      - run: echo json=${{ needs.containr.outputs.json }}
      - run: which jq
      - run: echo name=${{ fromJSON(needs.containr.outputs.json).name }}
